-   name: ACL | User folder | www-data user
    acl: "name=/home/{{ user }} entity=www-data etype=user permissions=r-x state=present"
-   name: ACL | User folder | www-data group
    acl: "name=/home/{{ user }} entity=www-data etype=group permissions=r-x state=present"
#-   name: ACL | Deploy folder | www-data user
#    acl: "name={{ ansistrano_deploy_to }} entity=www-data etype=user permissions=r-x recursive=true default=yes state=present"
#-   name: ACL | Deploy folder | www-data group
#    acl: "name={{ ansistrano_deploy_to }} entity=www-data etype=group permissions=r-x recursive=true default=yes state=present"
-   name: Symfony | Composer install
    composer:
        command: install
        global_command: false
        working_dir: "{{ ansistrano_release_path.stdout }}"
        optimize_autoloader: true
-   name: Symfony | .env.local
    template:
        src: env.j2
        dest: "{{ ansistrano_shared_path }}/.env.local"
-   name: ACL | Symfony var folder | www-data user
    acl: "name={{ ansistrano_shared_path }}/{{ item }} entity=www-data etype=user permissions=rwx recursive=true default=yes state=present"
    with_items: "{{ ansistrano_shared_paths }}"
-   name: ACL | Symfony var folder | www-data group
    acl: "name={{ ansistrano_shared_path }}/{{ item }} entity=www-data etype=group permissions=rwx recursive=true default=yes state=present"
    with_items: "{{ ansistrano_shared_paths }}"
-   name: ACL | Symfony var folder | frigodons user
    acl: "name={{ ansistrano_shared_path }}/{{ item }} entity=frigodons etype=user permissions=rwx recursive=true default=yes state=present"
    with_items: "{{ ansistrano_shared_paths }}"
-   name: ACL | Symfony var folder | frigodons group
    acl: "name={{ ansistrano_shared_path }}/{{ item }} entity=frigodons etype=group permissions=rwx recursive=true default=yes state=present"
    with_items: "{{ ansistrano_shared_paths }}"
-   name: NPM | Install packages
    npm:
        path: "{{ ansistrano_release_path.stdout }}"
        state: present
