-   name: Symfony | Composer install
    composer:
        command: install
        global_command: false
        working_dir: "{{ ansistrano_release_path.stdout }}"
        optimize_autoloader: true
-   name: Symfony | .env.local
    template:
        src: env.j2
        dest: "{{ ansistrano_shared_path }}/.env.local"
-   name: Symfony | www-data user ACL
    acl: "name={{ ansistrano_shared_path }}/{{ item }} entity=www-data etype=user permissions=rwX default=yes state=present"
    with_items: "{{ ansistrano_shared_paths }}"
-   name: Symfony | www-data group ACL
    acl: "name={{ ansistrano_shared_path }}/{{ item }} entity=www-data etype=group permissions=rwX default=yes state=present"
    with_items: "{{ ansistrano_shared_paths }}"
-   name: Symfony | frigodons user ACL
    acl: "name={{ ansistrano_shared_path }}/{{ item }} entity=frigodons etype=user permissions=rwX default=yes state=present"
    with_items: "{{ ansistrano_shared_paths }}"
-   name: Symfony | frigodons group ACL
    acl: "name={{ ansistrano_shared_path }}/{{ item }} entity=frigodons etype=group permissions=rwX default=yes state=present"
    with_items: "{{ ansistrano_shared_paths }}"
-   name: NPM | Install packages
    npm:
        path: "{{ ansistrano_release_path.stdout }}"
        state: present
