#-   name: Fix Ansistrano folders permissions
#    file:
#        dest: "{{ ansistrano_deploy_to }}"
#        mode: +x
#        recurse: true
-   name: Symfony | Composer install
    composer:
        command: install
        global_command: false
        working_dir: "{{ ansistrano_release_path.stdout }}"
        optimize_autoloader: true
-   name: Symfony | .env.local
    template:
        src: env.j2
        dest: "{{ ansistrano_shared_path }}/.env.local"
#-   name: Symfony | Setup directory permissions for var/
#    file:
#        path: "{{ ansistrano_shared_path }}/{{ item }}"
#        state: directory
#        mode: 0777
#        recurse: true
#        # We need it because logs are symlinks now
#        follow: yes
#    become: true
#    become_user: root
#    with_items: "{{ ansistrano_shared_paths }}"
-   name: NPM | Install packages
    npm:
        path: "{{ ansistrano_release_path.stdout }}"
        state: present
