---
-   name: Déploiement Frigodons
    hosts: all
    remote_user: root
    tasks:
        -   include_vars:
                file: vars.yml
        -   include_role:
                name: ansistrano.deploy
                apply:
                    become: true
                    become_user: "{{ user }}"
