---
-   name: Déploiement Frigodons
    hosts: all
    remote_user: frigodons
    tasks:
        -   include_vars:
                file: vars.yml
        -   include_vars:
                file: ./../../ansible/vars.yml
        -   include_role:
                name: ansistrano.deploy
