---
-   name: Déploiement Frigodons
    hosts: all
    remote_user: "{{ user }}"
    tasks:
        -   include_vars:
                file: vars.yml
        -   include_role:
                name: ansistrano.deploy
