---
-   name: Installation du serveur
    hosts: all
    remote_user: root
    tasks:
        -   include_vars:
                file: vars.yml
        -   name: USER | Création de {{ user }}
            user:
                name: "{{ user }}"
                shell: /bin/bash
        -   name: User | Clé SSH
            authorized_key:
                user: "{{ user }}"
                state: present
                key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
        -   name: APT | Update
            apt:
                upgrade: dist
                update_cache: yes
        -   include_role:
                name: firewall
        -   include_role:
                name: tools
        -   include_role:
                name: php
        -   include_role:
                name: pgsql
        -   include_role:
                name: nginx
        -   include_role:
                name: nodejs
        -   command: "git init --bare {{ ansistrano_deploy_to }}.git"
            args:
                creates: "{{ ansistrano_deploy_to }}.git"
            become: true
            become_user: "{{ user }}"
