user: frigodons
domain: frigodons.org
ansistrano_deploy_to: "/home/{{ user }}/{{ domain }}"
ansistrano_deploy_via: git
ansistrano_git_repo: "{{ ansistrano_deploy_to }}.git"
ansistrano_git_branch: main
ansistrano_keep_releases: 5
ansistrano_shared_paths: ["var"]
ansistrano_shared_files: [".env.local"]
ansistrano_before_symlink_shared_tasks_file: "{{ playbook_dir }}/tasks/before_symlink.yml"
ansistrano_after_symlink_shared_tasks_file: "{{ playbook_dir }}/tasks/after_symlink.yml"
ansistrano_after_symlink_tasks_file: "{{ playbook_dir }}/tasks/end.yml"
